# Generated by Django 4.1.5 on 2023-02-06 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_remove_book_owner_book_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
        migrations.AlterModelTable(
            name='bookgenre',
            table='book_genres',
        ),
        migrations.AlterModelTable(
            name='library',
            table='libraries',
        ),
        migrations.AlterModelTable(
            name='loan',
            table='loans',
        ),
        migrations.AlterModelTable(
            name='reader',
            table='readers',
        ),
    ]
