# Generated by Django 4.1.5 on 2023-02-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0001_initial'),
        ('holders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdergroup',
            name='readers',
            field=models.ManyToManyField(to='libraries.reader'),
        ),
    ]
