# Generated by Django 4.1.5 on 2023-02-07 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0003_alter_book_table_alter_bookgenre_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pageCount',
            new_name='page_count',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publicationDate',
            new_name='publication_date',
        ),
        migrations.AlterField(
            model_name='loan',
            name='expected_return_date',
            field=models.DateField(default=datetime.date(2023, 2, 28)),
        ),
    ]
