# Generated by Django 4.1.6 on 2023-05-23 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0005_bookgenre_created_at_bookgenre_lastmodified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='expected_return_date',
            field=models.DateField(default=datetime.date(2023, 6, 13)),
        ),
    ]
