# Generated by Django 4.1.5 on 2023-02-05 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraries', '0001_initial'),
        ('holders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdergroup',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holdergroup',
            name='holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='holders.holder'),
        ),
        migrations.AddField(
            model_name='holdergroup',
            name='readers',
            field=models.ManyToManyField(to='libraries.reader'),
        ),
    ]
