# Generated by Django 4.1.5 on 2023-02-06 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holders', '0003_remove_holdergroup_admin_holder_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='holder',
            table='holders',
        ),
        migrations.AlterModelTable(
            name='holdergroup',
            table='groups',
        ),
    ]
